# Tirgul 3

## Add nice equations using LaTEX syntax in Markdown
### Sphere or Quadratic equations::
$ x^2 + y^2 = z^2 \\$
$ \\ x_1,_2 =  \frac{- b\pm \sqrt{b^2-4ac}}{2a} $

In [25]:
import pandas as pd
data = pd.read_csv('titanic_short.csv')
data.head()

pclass  survived      age     sex
0    1st         1  29.0000  female
1    1st         0   2.0000  female
2    1st         0  30.0000    male
3    1st         0  25.0000  female
4    1st         1   0.9167    male

In [26]:
# is null - isna
dataIsNull = pd.isnull(data['age'])
dataIsNull

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13     True
14     True
15    False
16    False
17    False
18    False
19     True
20    False
21    False
22     True
23    False
24    False
25     True
26    False
27    False
28    False
29     True
Name: age, dtype: bool

In [27]:
# isna is exactly the same (due to historical reasons related to 'R' language)
dataIsna = pd.isna(data['age'])
dataIsna

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13     True
14     True
15    False
16    False
17    False
18    False
19     True
20    False
21    False
22     True
23    False
24    False
25     True
26    False
27    False
28    False
29     True
Name: age, dtype: bool

In [28]:
# we can present the data at these null rows
filteredData = data[pd.isna(data['age'])]
filteredData

pclass  survived  age     sex
12    1st         1  NaN  female
13    1st         1  NaN    male
14    1st         0  NaN    male
19    1st         1  NaN  female
22    1st         1  NaN    male
25    1st         0  NaN    male
29    1st         0  NaN    male

In [29]:
# What if we want to only the cell with no null:
# we could us the ~ operate
filteredData = data[~pd.isna(data['age'])]
filteredData.head(13)

pclass  survived      age     sex
0     1st         1  29.0000  female
1     1st         0   2.0000  female
2     1st         0  30.0000    male
3     1st         0  25.0000  female
4     1st         1   0.9167    male
5     1st         1  47.0000    male
6     1st         1  63.0000  female
7     1st         0  39.0000    male
8     1st         1  58.0000  female
9     1st         0  71.0000    male
10    1st         0  47.0000    male
11    1st         1  19.0000  female
15    1st         1  50.0000  female

In [30]:
# or the notnull command
filteredData = data[pd.notnull(data['age'])]
filteredData.head(13)

pclass  survived      age     sex
0     1st         1  29.0000  female
1     1st         0   2.0000  female
2     1st         0  30.0000    male
3     1st         0  25.0000  female
4     1st         1   0.9167    male
5     1st         1  47.0000    male
6     1st         1  63.0000  female
7     1st         0  39.0000    male
8     1st         1  58.0000  female
9     1st         0  71.0000    male
10    1st         0  47.0000    male
11    1st         1  19.0000  female
15    1st         1  50.0000  female

In [31]:
# Mean
dataAge = data['age']
dataAge.mean()

34.90942173913044

In [32]:
dataAge.min()

0.9167

In [33]:
dataAge.max()

71.0

In [34]:
dataAge.median()

30.0

## Numpy
Matrices and much more, this is where the fun begins..

[Numpy official docs](https://numpy.org/doc/stable/reference/index.html)

In [35]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr*arr)

[ 1  4  9 16 25]


In [36]:
#### vector multiplication (AKA dot producdt)
print("arr.dot(arr)\t=",arr.dot(arr))
# or by 
print("arr@arr\t\t=",arr@arr)


arr.dot(arr)	= 55
arr@arr		= 55


In [37]:
# create ones matrix of specific size:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
# self excercise: create zeros matrix of specific size:






In [39]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
# The I matrix
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
# self excercise: create the following 3X3 diagonal matrix
#  [1., 0., 0.],
#  [0., 2., 0.],
#  [0., 0., 3.]








In [42]:
print([1,2,3]*np.eye(3))

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [43]:
# Another Way
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [44]:
# random
e = np.random.random((2,4)) 
print(e)

[[0.74738624 0.61785783 0.22894666 0.82370343]
 [0.45945422 0.05077788 0.30786927 0.38762231]]


In [45]:
# append
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([11, 12, 13, 14, 15])
arr3 = np.append(arr1,arr2)
print(arr3)


[ 1  2  3  4  5 11 12 13 14 15]


In [46]:
# we can add arrays of same shape
print(arr1+arr2)

[12 14 16 18 20]


In [47]:
# However arrays must have same size
arr3 = np.array([1,2])
print(arr1+arr3) # ERROR

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [ ]:
# self excercise: Assume hypothethical case where you wish for each student to calculate average of the highest 5 grades out of 6 student's assignment
# step 1. generate 10X6 random integer numbers between 70 to 100 to represent students grades
# step 2. calculate mean of top 5 grades for each student








In [48]:
numCols = 6
grades = np.random.randint(70,100,size=(10,numCols))
print(grades)

[[98 90 73 98 95 83]
 [91 76 77 87 98 78]
 [95 72 95 73 82 91]
 [98 95 99 75 70 89]
 [82 78 77 77 84 93]
 [94 74 85 83 81 72]
 [92 80 78 98 80 85]
 [80 73 77 77 96 73]
 [84 97 84 75 98 82]
 [92 89 77 73 99 98]]


In [49]:
top5Avg = (grades.sum(axis=1)-grades.min(axis=1)) / (numCols-1)
top5Avg = top5Avg.reshape(len(top5Avg),1) # for display purpose
print(top5Avg)

[[92.8]
 [86.2]
 [87.2]
 [91.2]
 [82.8]
 [83.4]
 [87. ]
 [80.6]
 [89. ]
 [91. ]]
